AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  iot-epd-signage

  Sample SAM Template for iot-epd-signage

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 10
    MemorySize: 128

Parameters:
  AzureTenantID:
    Type: String
  AzureAppID:
    Type: String
  AzureAppSecret:
    Type: String
  AzureUserPrincipalName:
    Type: String

Resources:
  CalendarFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: calendar/
      Handler: app.lambda_handler
      Runtime: ruby3.2
      Policies:
        - arn:aws:iam::aws:policy/AWSIoTDataAccess
      Environment:
        Variables:
          AZURE_TENANT_ID: !Ref AzureTenantID
          AZURE_APP_ID: !Ref AzureAppID
          AZURE_APP_SECRET: !Ref AzureAppSecret
          AZURE_USER_PRINCIPAL_NAME: !Ref AzureUserPrincipalName
          TZ: Asia/Tokyo
      Architectures:
        - x86_64
      Events:
        IoTRule:
          Type: IoTRule
          Properties:
            Sql: SELECT * FROM 'iot-epd-signage/started'
        Schedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: cron(* * ? * * *)
            ScheduleExpressionTimezone: Japan

Outputs:
  CalendarFunction:
    Description: "Calendar Lambda Function ARN"
    Value: !GetAtt CalendarFunction.Arn
  CalendarFunctionIamRole:
    Description: "Implicit IAM Role created for Calendar function"
    Value: !GetAtt CalendarFunctionRole.Arn
